apiVersion: 1
kind: Pod
metadata:
  name: ambassador-example
spec:
  containers:
    # This is where main app should go
    # - name: test
    #   image test
    - name: twemproxy
      image: ganomede/twemproxy
      command:
      - "nutcracker"
      - "-c"
      - "/etc/config/nutcracker.yaml"
      - "-v"
      - "7"
      - "-s"
      - "6222"
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: conifg-volume
      configMap:
        name: twm-config
