apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharded-redis
  labels:
    app: sharded-redis
    # matchLabels:
    #   app: sharded-redis
spec:
  serviceName: "redis"
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
  selector:
    matchLabels:
      app: redis
